# __Author__      = " Jacob Paul "
# Description     = " Docker Compose to run the CNC-API Django project with Mongo and Redis Containers in same network "

version: '3'

services:

  backend:
    image: "siqsessedge/cnc-api:CNC-v6.0"
    environment:
      "ApplicationMode" : "web"
    ports:
      - "8000:8000"
    volumes:
      - "./DockerFiles/JsonDataBase/:/cnc/App/LiveJsonDataBase/"
      - "./DockerFiles/JsonConfiguration/:/cnc/App/JsonConfiguration/"
      - "./DockerFiles/ExcelProduction:/cnc/App/Excel"

    depends_on:
      - redis
      - mongo
    networks:
      cnc-network:
        ipv4_address: 174.22.0.2
    restart: always

  redis:
    image: "redis:5"
    ports:
      - "6379:6379"
    networks:
      cnc-network:
        ipv4_address: 174.22.0.3
    restart: always

  mongo:
    image: "mongo:bionic"
    ports:
      - "27016:27017"
    volumes:
      - './DockerFiles/MongoDB/data:/data/db'

    networks:
      cnc-network:
        ipv4_address: 174.22.0.4
    restart: always

networks:
  cnc-network:
    ipam:
      config:
        - subnet: 174.22.0.0/16

