# __Author__      = " Jacob Paul "
# Discription     = " Docker Compose to run the CNC-API Django project with Mongo and Redis Containers in same network ""

version: '3'

services:

  backend:
    image: "siqsessedge/cnc-api:v2"
    ports:
      - "8000:8000"
    depends_on: 
      - redis
      - mongo
    networks:
      cnc-network:
        ipv4_address: 174.22.0.3
    restart: always

  redis:
    image: "redis:5"
    ports:
      - "6379:6379"
    networks:
      cnc-network:
        ipv4_address: 174.22.0.4
    restart: always

  mongo:
    image: "mongo:latest"
    ports:
      - "27016:27017"
    networks:
      cnc-network:
        ipv4_address: 174.22.0.2
    restart: always

networks:
  cnc-network:
    ipam:
      config:
        - subnet: 174.22.0.0/16
